---
# handlers file for roles/elk
- name: restart elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    state: restarted

- name: restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: restart kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted

- name: Restart SSH
  systemd:
    name: ssh
    state: restarted

- name: Reload UFW
  ufw:
    state: reloaded