---
- name: Установка Elasticsearch
  become: yes
  become_method: sudo
  include: install_elasticsearch.yml

- name: Установка Logstash
  become: yes
  become_method: sudo
  include: install_logstash.yml

- name: Установка kibana
  become: yes
  become_method: sudo
  include: install_kibana.yml

- name: Установка nginx для kibana 8080
  become: yes
  become_method: sudo
  include: setup_nginx_for_kibana.yml

- name: Установка ufw ssh
  become: yes
  become_method: sudo
  include: install_system.yml

