---
# Убедимся что Kibana APT repository key добавлен
- name: Добавим Kibana APT repository key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

# Убедимся что Kibana APT repository добавлен
- name: Добавим Kibana APT repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

# Обновим APT cache
- name: Обновим APT cache
  apt:
    update_cache: yes

# Установим Kibana
- name: Установка Kibana 8.х
  apt:
    name: kibana
    state: present
  register: kibana_install_status

# Проверим Kibana service запущен
- name: Проверим что Kibana service запщен
  systemd:
    name: kibana
    state: started
  register: kibana_service_status

# Переставляем Kibana если сервис не был запущен
- name: Переставляем Kibana если сервис не был запущен
  apt:
    name: kibana
    state: present
  when: kibana_service_status.changed

# Проверим что Kibana service включен и запущен
- name: Проверим что Kibana service включен и запущен
  systemd:
    name: kibana
    enabled: yes
    state: started

- name: Установка server.port значение 0.0.0.0 в kibana.yml
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?\s?server.port:.*$'
    line: 'server.port: 5601'

- name: Set server.host to 0.0.0.0 in kibana.yml
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?\s?server.host:.*$'
    line: 'server.host: "0.0.0.0"'

- name: Заносим значение в поле elasticsearch.ports в kibana.yml
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#?\s?elasticsearch.hosts:.*$'
    line: 'elasticsearch.hosts: ["http://192.168.1.206:9200"]'

- name: Отключаем ssl (test) в node.options
  lineinfile:
    path: /etc/kibana/node.options
    regexp: '^#?\s?--openssl-legacy-provider$'
    line: '##--openssl-legacy-provider'
    backrefs: yes

- name: Включение и запуск kibana как systemd service
  systemd:
    enabled: yes
    name: kibana
    daemon_reload: yes
    state: restarted

