---
# handlers file for roles/lemp
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Restart SSH
      systemd:
        name: ssh
        state: restarted

    - name: Reload UFW
      ufw:
        state: reloaded