---
# tasks file for roles/filebeat
# Filebeat Настройка
    - name: Проверка что Filebeat service запущен
      systemd:
        name: filebeat
        state: started
      register: filebeat_service_status
      ignore_errors: yes

    - name: Добавляем Elasticsearch APT repository key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Добавляем Elasticsearch APT repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

    - name: Обновление APT cache
      apt:
        update_cache: yes

    - name: Установка Filebeat через APT
      apt:
        name: filebeat=8.15.0
        state: present
      when: filebeat_service_status.changed or (ansible_facts.packages['filebeat'] is not defined)

    - name: Включаем и устанавливаем nginx модуль для Filebeat
      command: 
        cmd: filebeat modules enable nginx
      notify:
        - restart filebeat


    - name: Копируем Filebeat config файл
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        mode: '0644'
      notify:
        - restart filebeat

    - name: Копируем nginx module config файл
      template:
        src: nginx.yml.j2
        dest: /etc/filebeat/modules.d/nginx.yml
        mode: '0644'
      notify:
        - restart filebeat

    - name: Проверка что Filebeat service включен и запущен
      systemd:
        name: filebeat
        enabled: yes
        state: started

